### PR TITLE
SUNDAY UPDATE

### PR DESCRIPTION
**Pull request by mrrizkin**
I coded this pull request, without testing with real data from API.

please give a feedback.

### CODE REVIEW

**Comment by mrrizkin** [comment]
wait, there's a bug

**Comment by mrrizkin** [comment]
ok, it fixed now

**Comment by mrrizkin** [comment]
if jenis transaksi is open, you can input nominal deposit. otherwise, it will automaticly make deposit with nominal that already present

**Comment by aribrilliantsyah** [comment]
Oke, you saved my day

**Pull request merged**
